---

- name: Install marathon-lb load balancer
  command: dcos package install --yes marathon-lb

- name: Wait a bit for the package install to complete
  pause: seconds=30

- name: Scale the martathon-lb to run on each public agent
  command: dcos marathon app update /marathon-lb instances="{{ groups['tag_dcos_slave_public'] | length }}"

- debug: var=dcos_install_demo_sd_and_lb_nginx verbosity=1

- name: Install demo Service Discovery and load balancing on nginx
  include: demos/service_discovery_and_load_balancing/install_demo.yml
  when: dcos_install_demo_sd_and_lb_nginx == true

- debug: var=dcos_install_demo_tutum_hello_world verbosity=1

- name: Insstall demo Tutum hello-world
  include: demos/tutum_hello_world/install_demo.yml
  when: dcos_install_demo_tutum_hello_world == true

