---

- name: Copy 'dockercloud.json' to controller host.
  copy: src=demos/dockercloud_hello_world/dockercloud.json dest=./dockercloud.json mode=0440

- name: Launch external Dockercloud hello-world sample application.
  command: dcos marathon app add ./dockercloud.json

